### PR TITLE
Update index.js

### PR DESCRIPTION
**Pull request by arashrasoulzadeh**
get a reference to map

access it like this : 
                <CedarMaps
                    ref={(ref) => (this.map = ref)}
                </CedarMaps>

this.map.map is the real mapboxGL

### CODE REVIEW

**Comment by arashrasoulzadeh** [comment]
please accept this

**Comment by sinaabadi** [comment]
@arashrasoulzadeh Please explain what you want to achieve with this pull request.

**Comment by arashrasoulzadeh** [comment]
you need reference to Mapbox for functions like geCenter() and ...

**Comment by sinaabadi** [comment]
@arashrasoulzadeh Please update `README` and also provide `getter function` for map instance

**Pull request closed without merging**
